name: Build Easycontrol Android App

on:
  workflow_dispatch:  # 允许手动触发
    inputs:
      build-type:
        description: '选择构建类型 (debug 或 release)'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./easycontrol/gradlew
      
    - name: Build with Gradle
      run: |
        cd easycontrol
        ./gradlew assemble${{ github.event.inputs.build-type == 'release' ? 'Release' : 'Debug' }}
      env:
        CI: false  # 禁用CI模式以避免某些检查
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: easycontrol-${{ github.event.inputs.build-type }}-apk
        path: easycontrol/app/build/outputs/apk/${{ github.event.inputs.build-type }}/*.apk
        retention-days: 7
