name: Build Easycontrol Android App

on:
  workflow_dispatch:  # 允许手动触发
    inputs:
      build-type:
        description: 'Select build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./easycontrol/gradlew
      
    - name: Determine build task
      id: determine-build
      run: |
        if [ "${{ github.event.inputs.build-type }}" = "release" ]; then
          echo "BUILD_TASK=assembleRelease" >> $GITHUB_OUTPUT
          echo "APK_PATH=release" >> $GITHUB_OUTPUT
        else
          echo "BUILD_TASK=assembleDebug" >> $GITHUB_OUTPUT
          echo "APK_PATH=debug" >> $GITHUB_OUTPUT
        fi
        
    - name: Build with Gradle
      run: |
        cd easycontrol
        ./gradlew ${{ steps.determine-build.outputs.BUILD_TASK }}
      env:
        CI: false
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: easycontrol-${{ github.event.inputs.build-type }}-apk
        path: easycontrol/app/build/outputs/apk/${{ steps.determine-build.outputs.APK_PATH }}/*.apk
        retention-days: 7
