name: Android CI with Manual Trigger

on:
  # 自动触发条件（保留原有）
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # 手动触发配置
  workflow_dispatch:
    inputs:
      build-type:
        description: '构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
      upload-artifact:
        description: '上传构建产物'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        BUILD_TYPE=${{ github.event.inputs.build-type || 'debug' }}
        ./gradlew assemble${{ github.event.inputs.build-type || 'Debug' }}
    
    - name: Upload APK artifact
      if: ${{ github.event.inputs.upload-artifact != 'false' }}
      uses: actions/upload-artifact@v4
      with:
        name: easycontrol-app-${{ github.event.inputs.build-type || 'debug' }}
        path: app/build/outputs/apk/${{ github.event.inputs.build-type || 'debug' }}/app-${{ github.event.inputs.build-type || 'debug' }}.apk
